#!/usr/bin/env python3
"""Generate tiered Condor submit files for Grid codegen smoke runs.

The generated files encode the resource strategy learned from CRC smoke tests:
logs and wrappers live under /users/lhu1, training code/configs live under the
shared project root, and GPU/memory requests are split by tier instead of using
one static request for every machine class.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Tier:
    name: str
    memory_gb: int
    host_prefixes: tuple[str, ...]
    note: str


DEFAULT_TIERS = (
    Tier(
        name="h100_only_12gb",
        memory_gb=12,
        host_prefixes=("qa-h100-",),
        note="H100-only escalation tier for benchmark/high-VRAM retries after L40S/A100-class OOM evidence.",
    ),
    Tier(
        name="h100_a100_l40s_12gb",
        memory_gb=12,
        host_prefixes=("qa-h100-", "qa-a100-", "qa-l40s-"),
        note="High-end condo GPUs. 12 GB is a slot-friendly smoke tier; monitor for host memory kills.",
    ),
    Tier(
        name="a40_rtx6k_16gb",
        memory_gb=16,
        host_prefixes=("qa-a40-", "qa-rtx6k-"),
        note="Mid/high public GPUs. Use only after confirming project path readability or using a readable bundle.",
    ),
    Tier(
        name="a10_16gb",
        memory_gb=16,
        host_prefixes=("qa-a10-",),
        note="Fallback tier. Previous 8 GB A10 smoke was cgroup-killed; use 16 GB and verify path permissions.",
    ),
)


def condor_requirement(prefixes: tuple[str, ...]) -> str:
    return "(" + " || ".join(f'regexp("{prefix}", Machine)' for prefix in prefixes) + ")"


def submit_text(
    *,
    campaign_name: str,
    run_id: str,
    remote_root: str,
    log_root: str,
    wrapper_path: str,
    tier: Tier,
    strategy: str,
    seed: int,
) -> str:
    remote_run = f"{remote_root}/campaigns/{campaign_name}/runs/{run_id}"
    log_dir = f"{log_root}/{campaign_name}/{run_id}"
    train_script = f"{remote_root}/shared/train.py"
    config_path = f"{remote_run}/train_config.json"
    req = condor_requirement(tier.host_prefixes)

    return f"""# Grid codegen smoke submit, resource tier: {tier.name}
# {tier.note}
# Generated by scripts/generate_tiered_condor_submits.py
universe                = vanilla
executable              = /bin/bash
arguments               = {wrapper_path} {train_script} --config {config_path}
getenv                  = True
environment             = "baseline_source_STRATEGY={strategy} PYTHONUNBUFFERED=1 baseline_source_SEED={seed}"
request_gpus            = 1
request_memory          = {tier.memory_gb} GB
request_disk            = 8 GB
requirements            = {req}
output                  = {log_dir}/condor.out
error                   = {log_dir}/condor.err
log                     = {log_dir}/condor.log
initialdir              = {log_dir}
should_transfer_files   = NO
on_exit_remove          = (ExitBySignal == False) && (ExitCode == 0)
+JobBatchName           = "{campaign_name}_{tier.name}"
queue 1
"""


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--campaign-name", required=True)
    p.add_argument("--run-id", required=True)
    p.add_argument("--remote-root", required=True)
    p.add_argument("--log-root", default="/users/lhu1/condor_grid_logs")
    p.add_argument("--wrapper-path", required=True)
    p.add_argument("--output-dir", required=True, type=Path)
    p.add_argument("--strategy", default="grid_smoke20_codegen")
    p.add_argument("--seed", type=int, default=1)
    p.add_argument(
        "--tiers",
        default="h100_only_12gb,h100_a100_l40s_12gb,a40_rtx6k_16gb,a10_16gb",
        help="Comma-separated tier names to generate.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    tiers_by_name = {tier.name: tier for tier in DEFAULT_TIERS}
    requested = [name.strip() for name in args.tiers.split(",") if name.strip()]
    unknown = [name for name in requested if name not in tiers_by_name]
    if unknown:
        raise SystemExit(f"Unknown tier(s): {', '.join(unknown)}")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name in requested:
        tier = tiers_by_name[name]
        path = args.output_dir / f"codegen_smoke_{tier.name}.submit"
        path.write_text(
            submit_text(
                campaign_name=args.campaign_name,
                run_id=args.run_id,
                remote_root=args.remote_root.rstrip("/"),
                log_root=args.log_root.rstrip("/"),
                wrapper_path=args.wrapper_path,
                tier=tier,
                strategy=args.strategy,
                seed=args.seed,
            )
        )
        written.append(path)

    for path in written:
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()



